apiVersion: v1
name: syslog-ng
description: Syslog-ng Helm Chart
version: 0.0.3
appVersion: 3.38.1
maintainers:
  - name: absentbri
sources:
  - https://github.com/absentbri/helm-charts
keywords:
  - Syslog
  - syslog-ng
