{{- if .Values.persistence.enable }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "syslog-ng.fullname" . }}-pvc
spec:
  accessModes: {{ .Values.persistence.accessModes | toYaml | nindent 4 }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
